name: The FeedWhack
favicon: null
layout_spectrum: 0.05567554500885308
typography_spectrum: 0.26954964199103415
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7009682678617537
  lightness: 0.6973813809454441
  saturation: 0.0849477737210691
  rhythmicContrast: 0.5703601380810142
purpose: []
